title: tech-toys-scratch2
hero_image: images/banner.png
description: tech-toys-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2019-04-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
